<?php

class GeoTarget {
	/**
	 * Return all of the available countries for geotargeting
	 * TODO: Move this out of CentralNoticeDB (or rename the class)
	 *
	 * @param string $code The language code to return the country list in
	 *
	 * @return array
	 */
	static function getCountriesList( $code ) {
		$countries = array();

		if ( is_callable( array( 'CountryNames', 'getNames' ) ) ) {
			// Retrieve the list of countries in user's language (via CLDR)
			$countries = CountryNames::getNames( $code );
		}

		// If not via CLDR, we have our own list
		if ( !$countries ) {
			// Use this as fallback if CLDR extension is not enabled
			$countries = array(
				'AF'=> 'Afghanistan',
				'AL'=> 'Albania',
				'DZ'=> 'Algeria',
				'AS'=> 'American Samoa',
				'AD'=> 'Andorra',
				'AO'=> 'Angola',
				'AI'=> 'Anguilla',
				'AQ'=> 'Antarctica',
				'AG'=> 'Antigua and Barbuda',
				'AR'=> 'Argentina',
				'AM'=> 'Armenia',
				'AW'=> 'Aruba',
				'AU'=> 'Australia',
				'AT'=> 'Austria',
				'AZ'=> 'Azerbaijan',
				'BS'=> 'Bahamas',
				'BH'=> 'Bahrain',
				'BD'=> 'Bangladesh',
				'BB'=> 'Barbados',
				'BY'=> 'Belarus',
				'BE'=> 'Belgium',
				'BZ'=> 'Belize',
				'BJ'=> 'Benin',
				'BM'=> 'Bermuda',
				'BT'=> 'Bhutan',
				'BO'=> 'Bolivia',
				'BA'=> 'Bosnia and Herzegovina',
				'BW'=> 'Botswana',
				'BV'=> 'Bouvet Island',
				'BR'=> 'Brazil',
				'IO'=> 'British Indian Ocean Territory',
				'BN'=> 'Brunei Darussalam',
				'BG'=> 'Bulgaria',
				'BF'=> 'Burkina Faso',
				'BI'=> 'Burundi',
				'KH'=> 'Cambodia',
				'CM'=> 'Cameroon',
				'CA'=> 'Canada',
				'CV'=> 'Cape Verde',
				'KY'=> 'Cayman Islands',
				'CF'=> 'Central African Republic',
				'TD'=> 'Chad',
				'CL'=> 'Chile',
				'CN'=> 'China',
				'CX'=> 'Christmas Island',
				'CC'=> 'Cocos (Keeling) Islands',
				'CO'=> 'Colombia',
				'KM'=> 'Comoros',
				'CD'=> 'Congo, Democratic Republic of the',
				'CG'=> 'Congo',
				'CK'=> 'Cook Islands',
				'CR'=> 'Costa Rica',
				'CI'=> 'Côte d\'Ivoire',
				'HR'=> 'Croatia',
				'CU'=> 'Cuba',
				'CY'=> 'Cyprus',
				'CZ'=> 'Czech Republic',
				'DK'=> 'Denmark',
				'DJ'=> 'Djibouti',
				'DM'=> 'Dominica',
				'DO'=> 'Dominican Republic',
				'EC'=> 'Ecuador',
				'EG'=> 'Egypt',
				'SV'=> 'El Salvador',
				'GQ'=> 'Equatorial Guinea',
				'ER'=> 'Eritrea',
				'EE'=> 'Estonia',
				'ET'=> 'Ethiopia',
				'FK'=> 'Falkland Islands (Malvinas)',
				'FO'=> 'Faroe Islands',
				'FJ'=> 'Fiji',
				'FI'=> 'Finland',
				'FR'=> 'France',
				'GF'=> 'French Guiana',
				'PF'=> 'French Polynesia',
				'TF'=> 'French Southern Territories',
				'GA'=> 'Gabon',
				'GM'=> 'Gambia',
				'GE'=> 'Georgia',
				'DE'=> 'Germany',
				'GH'=> 'Ghana',
				'GI'=> 'Gibraltar',
				'GR'=> 'Greece',
				'GL'=> 'Greenland',
				'GD'=> 'Grenada',
				'GP'=> 'Guadeloupe',
				'GU'=> 'Guam',
				'GT'=> 'Guatemala',
				'GW'=> 'Guinea-Bissau',
				'GN'=> 'Guinea',
				'GY'=> 'Guyana',
				'HT'=> 'Haiti',
				'HM'=> 'Heard Island and McDonald Islands',
				'VA'=> 'Holy See (Vatican City State)',
				'HN'=> 'Honduras',
				'HK'=> 'Hong Kong',
				'HU'=> 'Hungary',
				'IS'=> 'Iceland',
				'IN'=> 'India',
				'ID'=> 'Indonesia',
				'IR'=> 'Iran',
				'IQ'=> 'Iraq',
				'IE'=> 'Ireland',
				'IL'=> 'Israel',
				'IT'=> 'Italy',
				'JM'=> 'Jamaica',
				'JP'=> 'Japan',
				'JO'=> 'Jordan',
				'KZ'=> 'Kazakhstan',
				'KE'=> 'Kenya',
				'KI'=> 'Kiribati',
				'KW'=> 'Kuwait',
				'KG'=> 'Kyrgyzstan',
				'LA'=> 'Lao People\'s Democratic Republic',
				'LV'=> 'Latvia',
				'LB'=> 'Lebanon',
				'LS'=> 'Lesotho',
				'LR'=> 'Liberia',
				'LY'=> 'Libyan Arab Jamahiriya',
				'LI'=> 'Liechtenstein',
				'LT'=> 'Lithuania',
				'LU'=> 'Luxembourg',
				'MO'=> 'Macao',
				'MK'=> 'Macedonia, Republic of',
				'MG'=> 'Madagascar',
				'MW'=> 'Malawi',
				'MY'=> 'Malaysia',
				'MV'=> 'Maldives',
				'ML'=> 'Mali',
				'MT'=> 'Malta',
				'MH'=> 'Marshall Islands',
				'MQ'=> 'Martinique',
				'MR'=> 'Mauritania',
				'MU'=> 'Mauritius',
				'YT'=> 'Mayotte',
				'MX'=> 'Mexico',
				'FM'=> 'Micronesia',
				'MD'=> 'Moldova, Republic of',
				'MC'=> 'Moldova',
				'MN'=> 'Mongolia',
				'ME'=> 'Montenegro',
				'MS'=> 'Montserrat',
				'MA'=> 'Morocco',
				'MZ'=> 'Mozambique',
				'MM'=> 'Myanmar',
				'NA'=> 'Namibia',
				'NR'=> 'Nauru',
				'NP'=> 'Nepal',
				'AN'=> 'Netherlands Antilles',
				'NL'=> 'Netherlands',
				'NC'=> 'New Caledonia',
				'NZ'=> 'New Zealand',
				'NI'=> 'Nicaragua',
				'NE'=> 'Niger',
				'NG'=> 'Nigeria',
				'NU'=> 'Niue',
				'NF'=> 'Norfolk Island',
				'KP'=> 'North Korea',
				'MP'=> 'Northern Mariana Islands',
				'NO'=> 'Norway',
				'OM'=> 'Oman',
				'PK'=> 'Pakistan',
				'PW'=> 'Palau',
				'PS'=> 'Palestinian Territory',
				'PA'=> 'Panama',
				'PG'=> 'Papua New Guinea',
				'PY'=> 'Paraguay',
				'PE'=> 'Peru',
				'PH'=> 'Philippines',
				'PN'=> 'Pitcairn',
				'PL'=> 'Poland',
				'PT'=> 'Portugal',
				'PR'=> 'Puerto Rico',
				'QA'=> 'Qatar',
				'RE'=> 'Reunion',
				'RO'=> 'Romania',
				'RU'=> 'Russian Federation',
				'RW'=> 'Rwanda',
				'SH'=> 'Saint Helena',
				'KN'=> 'Saint Kitts and Nevis',
				'LC'=> 'Saint Lucia',
				'PM'=> 'Saint Pierre and Miquelon',
				'VC'=> 'Saint Vincent and the Grenadines',
				'WS'=> 'Samoa',
				'SM'=> 'San Marino',
				'ST'=> 'Sao Tome and Principe',
				'SA'=> 'Saudi Arabia',
				'SN'=> 'Senegal',
				'CS'=> 'Serbia and Montenegro',
				'RS'=> 'Serbia',
				'SC'=> 'Seychelles',
				'SL'=> 'Sierra Leone',
				'SG'=> 'Singapore',
				'SK'=> 'Slovakia',
				'SI'=> 'Slovenia',
				'SB'=> 'Solomon Islands',
				'SO'=> 'Somalia',
				'ZA'=> 'South Africa',
				'KR'=> 'South Korea',
				'SS'=> 'South Sudan',
				'ES'=> 'Spain',
				'LK'=> 'Sri Lanka',
				'SD'=> 'Sudan',
				'SR'=> 'Suriname',
				'SJ'=> 'Svalbard and Jan Mayen',
				'SZ'=> 'Swaziland',
				'SE'=> 'Sweden',
				'CH'=> 'Switzerland',
				'SY'=> 'Syrian Arab Republic',
				'TW'=> 'Taiwan',
				'TJ'=> 'Tajikistan',
				'TZ'=> 'Tanzania',
				'TH'=> 'Thailand',
				'TL'=> 'Timor-Leste',
				'TG'=> 'Togo',
				'TK'=> 'Tokelau',
				'TO'=> 'Tonga',
				'TT'=> 'Trinidad and Tobago',
				'TN'=> 'Tunisia',
				'TR'=> 'Turkey',
				'TM'=> 'Turkmenistan',
				'TC'=> 'Turks and Caicos Islands',
				'TV'=> 'Tuvalu',
				'UG'=> 'Uganda',
				'UA'=> 'Ukraine',
				'AE'=> 'United Arab Emirates',
				'GB'=> 'United Kingdom',
				'UM'=> 'United States Minor Outlying Islands',
				'US'=> 'United States',
				'UY'=> 'Uruguay',
				'UZ'=> 'Uzbekistan',
				'VU'=> 'Vanuatu',
				'VE'=> 'Venezuela',
				'VN'=> 'Vietnam',
				'VG'=> 'Virgin Islands, British',
				'VI'=> 'Virgin Islands, U.S.',
				'WF'=> 'Wallis and Futuna',
				'EH'=> 'Western Sahara',
				'YE'=> 'Yemen',
				'ZM'=> 'Zambia',
				'ZW'=> 'Zimbabwe'
			);
		}

		// And we need to add MaxMind specific countries: http://www.maxmind.com/en/iso3166
		$countries['EU'] = wfMessage('centralnotice-country-eu')->inContentLanguage()->text();
		$countries['AP'] = wfMessage('centralnotice-country-ap')->inContentLanguage()->text();
		$countries['A1'] = wfMessage('centralnotice-country-a1')->inContentLanguage()->text();
		$countries['A2'] = wfMessage('centralnotice-country-a2')->inContentLanguage()->text();
		$countries['O1'] = wfMessage('centralnotice-country-o1')->inContentLanguage()->text();

		// We will also add country 'XX' which is a MW specific 'fake' country for when GeoIP
		// does not return any results at all or when something else odd has happened (IE: we
		// fail to parse the country.)
		$countries['XX'] = wfMessage('centralnotice-country-unknown')->inContentLanguage()->text();

		asort( $countries );

		return $countries;
	}
}
