-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-cn_notice_projects-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__cn_notice_projects AS
SELECT
  np_notice_id,
  np_project
FROM /*_*/cn_notice_projects;

DROP TABLE /*_*/cn_notice_projects;


CREATE TABLE /*_*/cn_notice_projects (
  np_notice_id INTEGER UNSIGNED NOT NULL,
  np_project VARCHAR(32) NOT NULL,
  PRIMARY KEY(np_notice_id, np_project)
);

INSERT INTO /*_*/cn_notice_projects (np_notice_id, np_project)
SELECT
  np_notice_id,
  np_project
FROM
  /*_*/__temp__cn_notice_projects;

DROP TABLE /*_*/__temp__cn_notice_projects;
