-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-cn_notice_countries-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__cn_notice_countries AS
SELECT
  nc_notice_id,
  nc_country
FROM /*_*/cn_notice_countries;

DROP TABLE /*_*/cn_notice_countries;


CREATE TABLE /*_*/cn_notice_countries (
  nc_notice_id INTEGER UNSIGNED NOT NULL,
  nc_country VARCHAR(2) NOT NULL,
  PRIMARY KEY(nc_notice_id, nc_country)
);

INSERT INTO /*_*/cn_notice_countries (nc_notice_id, nc_country)
SELECT
  nc_notice_id,
  nc_country
FROM
  /*_*/__temp__cn_notice_countries;

DROP TABLE /*_*/__temp__cn_notice_countries;
