-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-cn_notice_regions-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX nr_notice_id_region;
CREATE TEMPORARY TABLE /*_*/__temp__cn_notice_regions AS
SELECT  nr_notice_id,  nr_region
FROM  /*_*/cn_notice_regions;
DROP  TABLE  /*_*/cn_notice_regions;
CREATE TABLE  /*_*/cn_notice_regions (    nr_notice_id INTEGER UNSIGNED NOT NULL,    nr_region VARCHAR(6) NOT NULL,    PRIMARY KEY(nr_notice_id, nr_region)  );
INSERT INTO  /*_*/cn_notice_regions (nr_notice_id, nr_region)
SELECT  nr_notice_id,  nr_region
FROM  /*_*/__temp__cn_notice_regions;
DROP  TABLE /*_*/__temp__cn_notice_regions;